%define sys_restart_syscall	  0
%define sys_exit		  1
%define sys_fork		  2
%define sys_read		  3
%define sys_write		  4
%define sys_open		  5
%define sys_close		  6
%define sys_waitpid		  7
%define sys_creat		  8
%define sys_link		  9
%define sys_unlink		 10
%define sys_execve		 11
%define sys_chdir		 12
%define sys_time		 13
%define sys_mknod		 14
%define sys_chmod		 15
%define sys_lchown		 16
%define sys_oldstat		 18
%define sys_lseek		 19
%define sys_getpid		 20
%define sys_mount		 21
%define sys_umount		 22
%define sys_setuid		 23
%define sys_getuid		 24
%define sys_stime		 25
%define sys_ptrace		 26
%define sys_alarm		 27
%define sys_oldfstat		 28
%define sys_pause		 29
%define sys_utime		 30
%define sys_access		 33
%define sys_nice		 34
%define sys_sync		 36
%define sys_kill		 37
%define sys_rename		 38
%define sys_mkdir		 39
%define sys_rmdir		 40
%define sys_dup		 41
%define sys_pipe		 42
%define sys_times		 43
%define sys_brk		 45
%define sys_setgid		 46
%define sys_getgid		 47
%define sys_signal		 48
%define sys_geteuid		 49
%define sys_getegid		 50
%define sys_acct		 51
%define sys_umount2		 52
%define sys_ioctl		 54
%define sys_fcntl		 55
%define sys_setpgid		 57
%define sys_umask		 60
%define sys_chroot		 61
%define sys_ustat		 62
%define sys_dup2		 63
%define sys_getppid		 64
%define sys_getpgrp		 65
%define sys_setsid		 66
%define sys_sigaction		 67
%define sys_sgetmask		 68
%define sys_ssetmask		 69
%define sys_setreuid		 70
%define sys_setregid		 71
%define sys_sigsuspend		 72
%define sys_sigpending		 73
%define sys_sethostname	 74
%define sys_setrlimit		 75
%define sys_getrlimit		 76
%define sys_getrusage		 77
%define sys_gettimeofday	 78
%define sys_settimeofday	 79
%define sys_getgroups		 80
%define sys_setgroups		 81
%define sys_symlink		 83
%define sys_oldlstat		 84
%define sys_readlink		 85
%define sys_uselib		 86
%define sys_swapon		 87
%define sys_reboot		 88
%define sys_readdir		 89
%define sys_mmap		 90
%define sys_munmap		 91
%define sys_truncate		 92
%define sys_ftruncate		 93
%define sys_fchmod		 94
%define sys_fchown		 95
%define sys_getpriority	 96
%define sys_setpriority	 97
%define sys_statfs		 99
%define sys_fstatfs		100
%define sys_socketcall		102
%define sys_syslog		103
%define sys_setitimer		104
%define sys_getitimer		105
%define sys_stat		106
%define sys_lstat		107
%define sys_fstat		108
%define sys_olduname		109
%define sys_vhangup		111
%define sys_wait4		114
%define sys_swapoff		115
%define sys_sysinfo		116
%define sys_ipc		117
%define sys_fsync		118
%define sys_sigreturn		119
%define sys_clone		120
%define sys_setdomainname	121
%define sys_uname		122
%define sys_cacheflush		123
%define sys_adjtimex		124
%define sys_mprotect		125
%define sys_sigprocmask	126
%define sys_init_module	128
%define sys_delete_module	129
%define sys_quotactl		131
%define sys_getpgid		132
%define sys_fchdir		133
%define sys_bdflush		134
%define sys_sysfs		135
%define sys_personality	136
%define sys_setfsuid		138
%define sys_setfsgid		139
%define sys__llseek		140
%define sys_getdents		141
%define sys__newselect		142
%define sys_memfd_create	356
%define sys_waitid	284

